### This file is synced from the devops-github-sync repository.
### Changes should be made there and synced across.

repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.89.1
  hooks:
    - id: terraform_fmt
    - id: terraform_validate
    - id: terraform_tflint
      args:
        - --args=--disable-rule=terraform_required_version
        - --args=--disable-rule=terraform_required_providers

- repo: https://github.com/terraform-docs/terraform-docs
  rev: "v0.17.0"
  hooks:
    - id: terraform-docs-go
      name: "Terraform docs"
      args: ["markdown", "--output-file", "README-TF.md", "./"]
      always_run: true

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: check-merge-conflict
    - id: end-of-file-fixer
