name: Call PR Title Check

on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize
    branches:
      - develop

jobs:
  validate-title:
    uses: genopsx/devops-github-actions-workflows/.github/workflows/validate-pr-title.yml@main
    with:
      runs-on: ubuntu-latest
      branches: develop
    secrets:
      SEMANTIC_RELEASE_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
